<script>
const js_thml = () => {
	let code = "";
	code += "\n";
	code += "<html>\n";
	code += "\t<head>\n";
	code += "		<meta charset=\"utf-8\">\n";
	code += "		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
	code += "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
	code += "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	code += "		<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n";
	code += "\t\t<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n";
	code += "\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n";
	code += "		<title>\n";
	code += "		   index\n";
	code += "		</title>\n";
	code += "		<link rel=\"icon\" href=\"img/calicon.png\" type=\"image/png\" sizes=\"16x16\">\n";
	code += "		<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n";
	code += "\t\t<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n";
	code += "\t\t<link href=\"https://fonts.googleapis.com/css2?family=Work+Sans:wght@300&display=swap\" rel=\"stylesheet\">\n";
	code += "		<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\n";
	code += "		<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n";
	code += "		<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n";
	code += "		<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\n";
	code += "		<link rel=\"stylesheet\" href=\"css/navbar.css\"> \n";
	code += "		<link rel=\"stylesheet\" href=\"css/style.css\"> \n";
	code += "		<link rel=\"stylesheet\" href=\"css/footer.css\"> \n";
	code += "		<link href=\"https://unpkg.com/aos@2.3.1/dist/aos.css\" rel=\"stylesheet\">\n";
	code += "\t</head>\n";
	code += "\t<style>\n";
	code += "			img{\n";
	code += "			image-rendering: -moz-crisp-edges !important;\t   \n";
	code += "			image-rendering:   -o-crisp-edges !important;\t   \n";
	code += "			image-rendering: -webkit-optimize-contrast !important;\n";
	code += "			image-rendering: crisp-edges !important;\n";
	code += "			-ms-interpolation-mode: nearest-neighbor !important;\n";
	code += "		}\n";
	code += "\t</style>\n";
	code += "\t<body>\n";
	code += "		<header class=\"header\" id=\"header\">\n";
	code += "			<nav class=\"navbar navbar-default\">\n";
	code += "				<div class=\"container-fluid\">\n";
	code += "				  <!-- Brand and toggle get grouped for better mobile display -->\n";
	code += "				  <div class=\"navbar-header\">\n";
	code += "					<button type=\"button\" class=\"navbar-toggle plus collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-plus\">\n";
	code += "					<span class=\"icon-bar\"></span>\n";
	code += "					<span class=\"icon-bar\"></span>\n";
	code += "					<span class=\"icon-bar\"></span>\n";
	code += "					</button>\n";
	code += "					<a class=\"navbar-brand\" href=\"index.html\"><img src=\"img/logo/Asset 1SVG.svg\"></a>\n";
	code += "				  </div>\n";
	code += "			  \n";
	code += "				  <!-- Collect the nav links, forms, and other content for toggling -->\n";
	code += "				  <div class=\"collapse navbar-collapse\" id=\"navbar-collapse-plus\">\n";
	code += "					<ul class=\"nav navbar-nav nav-left-items\">\n";
	code += "					  <li><a href=\"all-sub-page/filters.html\">Propety </a></li>\n";
	code += "					  <li><a href=\"all-sub-page/finance.html\">Finance</a></li>\n";
	code += "					  <li><a href=\"all-sub-page/weit.html\">Education Portal</a></li>\n";
	code += "					  <li><a href=\"all-sub-page/rent.html\">For Rent</a></li>\n";
	code += "					  <li><a href=\"all-sub-page/price.html\">Price Atlas</a></li>\n";
	code += "					  <li><a href=\"all-sub-page/gratis.html\">Free Webinar</a></li>\n";
	code += "					</ul>\n";
	code += "\n";
	code += "					<ul class=\"nav navbar-nav navbar-right\">\n";
	code += "					  <li class=\"premium\"><a href=\"#\">Prenium</a></li>\n";
	code += "				\n";
	code += "					</ul>\n";
	code += "				  </div><!-- /.navbar-collapse -->\n";
	code += "				</div><!-- /.container-fluid -->\n";
	code += "			  </nav>\n";
	code += "			  <div class=\"dropup drop-tem\" style=\"position: fixed;bottom: 20px;left: 0;background: #fff !important;border-radius: 10px;\">\n";
	code += "				<button class=\"btn btn-primary dropdown-toggle\" type=\"button\" data-toggle=\"dropdown\" style=\"background: #fff !important;color:darkolivegreen;font-weight: bold;border-radius: 10px;outline: none !important;\">All Page\n";
	code += "				<span class=\"caret\"></span></button>\n";
	code += "				<ul class=\"dropdown-menu\">\n";
	code += "				  <li><a href=\"all-sub-page/beratung.html\">Beratung</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/learning.html\">Learning</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/object.html\">Object</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/blog.html\">Blog</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/subbblog.html\">Sub-blog</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/video.html\">Video</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/seminar.html\">Seminar</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/dashboard.html\">Dashboard</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/dbcourse.html\">DB-course</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/dbfavourite.html\">DB-favourite</a></li>\n";
	code += "				  <li><a href=\"all-sub-page/foreclosure.html\">Foreclosure</a></li>\n";
	code += "				</ul>\n";
	code += "			  </div>\n";
	code += "		</header>\n";
	code += "		<section class=\"top-section\">\n";
	code += "			\n";
	code += "\t\t\t  <div class=\"container\">\n";
	code += "				  <div class=\"row main-row\">\n";
	code += "					  <div class=\"col-md-6\">\n";
	code += "						<div class=\"jumbotron\" data-aos=\"fade-right\" data-aos-duration=\"1000\">\n";
	code += "							<div class=\"container\">\n";
	code += "								\n";
	code += "							 \n";
	code += "							<h2>Immobilling,Wohnugen,Hasur</h2>\n";
	code += "							<div class=\"row waswo\">\n";
	code += "								<div class=\"col-xs-6\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "									<p class=\"ttitle\">Was?</p>\n";
	code += "\t\t\t\t\t\t\t\t   <div class=\"custom-select\" style=\"width:100%\">\n";
	code += "									<select>\n";
	code += "									  <option value=\"0\">Select car:</option>\n";
	code += "									  <option value=\"1\">Audi</option>\n";
	code += "									  <option value=\"2\">BMW</option>\n";
	code += "									  <option value=\"3\">Citroen</option>\n";
	code += "									  <option value=\"4\">Ford</option>\n";
	code += "									  <option value=\"5\">Honda</option>\n";
	code += "									  <option value=\"6\">Jaguar</option>\n";
	code += "									  <option value=\"7\">Land Rover</option>\n";
	code += "									  <option value=\"8\">Mercedes</option>\n";
	code += "									  <option value=\"9\">Mini</option>\n";
	code += "									  <option value=\"10\">Nissan</option>\n";
	code += "									  <option value=\"11\">Toyota</option>\n";
	code += "									  <option value=\"12\">Volvo</option>\n";
	code += "									</select>\n";
	code += "								  </div>\n";
	code += "								</div>\n";
	code += "\n";
	code += "								<div class=\"col-xs-6\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "									<p class=\"ttitle\">Wo?</p>\n";
	code += "\t\t\t\t\t\t\t\t\t  <div class=\"custom-select\" style=\"width:100%\">\n";
	code += "									<select>\n";
	code += "									  <option value=\"0\">Select car:</option>\n";
	code += "									  <option value=\"1\">Audi</option>\n";
	code += "									  <option value=\"2\">BMW</option>\n";
	code += "									  <option value=\"3\">Citroen</option>\n";
	code += "									  <option value=\"4\">Ford</option>\n";
	code += "									  <option value=\"5\">Honda</option>\n";
	code += "									  <option value=\"6\">Jaguar</option>\n";
	code += "									  <option value=\"7\">Land Rover</option>\n";
	code += "									  <option value=\"8\">Mercedes</option>\n";
	code += "									  <option value=\"9\">Mini</option>\n";
	code += "									  <option value=\"10\">Nissan</option>\n";
	code += "									  <option value=\"11\">Toyota</option>\n";
	code += "									  <option value=\"12\">Volvo</option>\n";
	code += "									</select>\n";
	code += "								  </div>\n";
	code += "								</div>\n";
	code += "								\n";
	code += "							</div>\n";
	code += "							 <br>\n";
	code += "							  <div class=\"row secondselect\">\n";
	code += "								  <div class=\"col-sm-4\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "\t\t\t\t\t\t\t\t\t  <div class=\"custom-select\" style=\"width:100%\">\n";
	code += "										<select>\n";
	code += "										  <option value=\"0\">Select car:</option>\n";
	code += "										  <option value=\"1\">Audi</option>\n";
	code += "										  <option value=\"2\">BMW</option>\n";
	code += "										  <option value=\"3\">Citroen</option>\n";
	code += "										  <option value=\"4\">Ford</option>\n";
	code += "										  <option value=\"5\">Honda</option>\n";
	code += "										  <option value=\"6\">Jaguar</option>\n";
	code += "										  <option value=\"7\">Land Rover</option>\n";
	code += "										  <option value=\"8\">Mercedes</option>\n";
	code += "										  <option value=\"9\">Mini</option>\n";
	code += "										  <option value=\"10\">Nissan</option>\n";
	code += "										  <option value=\"11\">Toyota</option>\n";
	code += "										  <option value=\"12\">Volvo</option>\n";
	code += "										</select>\n";
	code += "									  </div>\n";
	code += "								  </div>\n";
	code += "								  <div class=\"col-sm-4\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "									<div class=\"custom-select\" style=\"width:100%\">\n";
	code += "										<select>\n";
	code += "										  <option value=\"0\">Select car:</option>\n";
	code += "										  <option value=\"1\">Audi</option>\n";
	code += "										  <option value=\"2\">BMW</option>\n";
	code += "										  <option value=\"3\">Citroen</option>\n";
	code += "										  <option value=\"4\">Ford</option>\n";
	code += "										  <option value=\"5\">Honda</option>\n";
	code += "										  <option value=\"6\">Jaguar</option>\n";
	code += "										  <option value=\"7\">Land Rover</option>\n";
	code += "										  <option value=\"8\">Mercedes</option>\n";
	code += "										  <option value=\"9\">Mini</option>\n";
	code += "										  <option value=\"10\">Nissan</option>\n";
	code += "										  <option value=\"11\">Toyota</option>\n";
	code += "										  <option value=\"12\">Volvo</option>\n";
	code += "										</select>\n";
	code += "									  </div>\n";
	code += "								</div>\n";
	code += "								<div class=\"col-sm-4\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "									<div class=\"custom-select\" style=\"width:100%\">\n";
	code += "										<select>\n";
	code += "										  <option value=\"0\">Select car:</option>\n";
	code += "										  <option value=\"1\">Audi</option>\n";
	code += "										  <option value=\"2\">BMW</option>\n";
	code += "										  <option value=\"3\">Citroen</option>\n";
	code += "										  <option value=\"4\">Ford</option>\n";
	code += "										  <option value=\"5\">Honda</option>\n";
	code += "										  <option value=\"6\">Jaguar</option>\n";
	code += "										  <option value=\"7\">Land Rover</option>\n";
	code += "										  <option value=\"8\">Mercedes</option>\n";
	code += "										  <option value=\"9\">Mini</option>\n";
	code += "										  <option value=\"10\">Nissan</option>\n";
	code += "										  <option value=\"11\">Toyota</option>\n";
	code += "										  <option value=\"12\">Volvo</option>\n";
	code += "										</select>\n";
	code += "									  </div>\n";
	code += "								</div>\n";
	code += "							  </div>\n";
	code += "\t\t\t\t\t\t\t <div class=\"row all-btn-search\">\n";
	code += "								 <div class=\"col-xs-12 allbtnsearcjcol\" style=\"padding-left: 8;padding-right: 8\">\n";
	code += "									 <div class=\"btn-group\" role=\"group\" aria-label=\"...\">\n";
	code += "										<button type=\"button\" class=\"btn btn-default\">Search</button>\n";
	code += "										<button type=\"button\" class=\"btn btn-default\">Create Search Request</button>\n";
	code += "									\n";
	code += "									  </div>\n";
	code += "								 </div>\n";
	code += "							 </div>\n";
	code += "							 </div>\n";
	code += "						  </div>\n";
	code += "					  </div>\n";
	code += "					  <div class=\"col-md-6\">\n";
	code += "\n";
	code += "					</div>\n";
	code += "				  </div>\n";
	code += "			  </div>\n";
	code += "		</section>\n";
	code += "\t\t<section class=\"apertment\" >\n";
	code += "\t\t\t  <div class=\"container\">\n";
	code += "				  <div class=\"row invest-now section-5\">\n";
	code += "					  <div class=\"heading-part\" data-aos=\"zoom-in-down\"  data-aos-duration=\"1000\">\n";
	code += "					  <h1>Featured Apartment</h1>\n";
	code += "					  <p>The Most frequently searched and most popular apartment of the application will be in the list</p>\n";
	code += "					</div>\n";
	code += "					<div  class=\"col-md-4 col-sm-6\">\n";
	code += "					\t<a style=\"text-decoration:none;\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\" data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"500\">\n";
	code += "							\t<p class=\"all-btn-p\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">1.2 km away</a></p>\n";
	code += "								<p class=\"all-btn-p-right\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">For sell</a></p>\n";
	code += "								<img class=\"main-image\" src=\"img/apert/1.jpg\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "								\t<div class=\"main-h\">\n";
	code += "								\t\t<img  src=\"img/apert/man.jpg\" alt=\"...\">\n";
	code += "								\t   \n";
	code += "									\t<h3><i class=\"bi bi-geo-alt\"></i>Knightsbridge</h3>\n";
	code += "										<h4>$2,500</h4>\n";
	code += "										<h5>Apartment London</h5>\n";
	code += "										<div class=\"name-bottom\">\n";
	code += "											<center>\n";
	code += "											<ul>\n";
	code += "												<li><span>2 <i class=\"fa fa-bed\"></i></span><br><span>Beadroom</span></li>\n";
	code += "												<li><span>2 <i class=\"fa fa-bath\"></i></span><br><span>Bathroom</span></li>\n";
	code += "												<li><span>1776 <i class=\"fa fa-square-o\"></i></span><br><span>Squre Ft</span></li>\n";
	code += "											</ul></center>\n";
	code += "										</div>\n";
	code += "									\t<p class=\"mainpokl\">Beautiful Huge I Familly House In Heart Of Wbstbury Newly Renovated With Furniture</p>\n";
	code += "										\n";
	code += "								\t</div>\n";
	code += "								\t<div class=\"all-re\" id=\"acolor\">\n";
	code += "										<p class=\"acolor\"><i class=\"bi bi-fullscreen-exit\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-heart\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-plus-circle\"></i></p>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "					<div  class=\"col-md-4 col-sm-6\">\n";
	code += "					\t<a style=\"text-decoration:none;\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\"  data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"700\">\n";
	code += "							\t<p class=\"all-btn-p\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">1.2 km away</a></p>\n";
	code += "								<p class=\"all-btn-p-right\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">For sell</a></p>\n";
	code += "								<img class=\"main-image\" src=\"img/apert/1.jpg\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "								\t<div class=\"main-h\">\n";
	code += "								\t\t<img  src=\"img/apert/man.jpg\" alt=\"...\">\n";
	code += "								\t   \n";
	code += "									\t<h3><i class=\"bi bi-geo-alt\"></i>Knightsbridge</h3>\n";
	code += "										<h4>$2,500</h4>\n";
	code += "										<h5>Apartment London</h5>\n";
	code += "										<div class=\"name-bottom\">\n";
	code += "											<center>\n";
	code += "											<ul>\n";
	code += "												<li><span>2 <i class=\"fa fa-bed\"></i></span><br><span>Beadroom</span></li>\n";
	code += "												<li><span>2 <i class=\"fa fa-bath\"></i></span><br><span>Bathroom</span></li>\n";
	code += "												<li><span>1776 <i class=\"fa fa-square-o\"></i></span><br><span>Squre Ft</span></li>\n";
	code += "											</ul></center>\n";
	code += "										</div>\n";
	code += "									\t<p class=\"mainpokl\">Beautiful Huge I Familly House In Heart Of Wbstbury Newly Renovated With Furniture</p>\n";
	code += "										\n";
	code += "								\t</div>\n";
	code += "								\t<div class=\"all-re\" id=\"acolor\">\n";
	code += "										<p class=\"acolor\"><i class=\"bi bi-fullscreen-exit\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-heart\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-plus-circle\"></i></p>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "					<div  class=\"col-md-4 col-sm-6\">\n";
	code += "					\t<a style=\"text-decoration:none;\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\"  data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"900\">\n";
	code += "							\t<p class=\"all-btn-p\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">1.2 km away</a></p>\n";
	code += "								<p class=\"all-btn-p-right\"><a href=\"#\" class=\"btn all-btn btn-default\" role=\"button\">For sell</a></p>\n";
	code += "								<img class=\"main-image\" src=\"img/apert/1.jpg\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "								\t<div class=\"main-h\">\n";
	code += "								\t\t<img  src=\"img/apert/man.jpg\" alt=\"...\">\n";
	code += "								\t   \n";
	code += "									\t<h3><i class=\"bi bi-geo-alt\"></i>Knightsbridge</h3>\n";
	code += "										<h4>$2,500</h4>\n";
	code += "										<h5>Apartment London</h5>\n";
	code += "										<div class=\"name-bottom\">\n";
	code += "											<center>\n";
	code += "											<ul>\n";
	code += "												<li><span>2 <i class=\"fa fa-bed\"></i></span><br><span>Beadroom</span></li>\n";
	code += "												<li><span>2 <i class=\"fa fa-bath\"></i></span><br><span>Bathroom</span></li>\n";
	code += "												<li><span>1776 <i class=\"fa fa-square-o\"></i></span><br><span>Squre Ft</span></li>\n";
	code += "											</ul></center>\n";
	code += "										</div>\n";
	code += "									\t<p class=\"mainpokl\">Beautiful Huge I Familly House In Heart Of Wbstbury Newly Renovated With Furniture</p>\n";
	code += "										\n";
	code += "								\t</div>\n";
	code += "								\t<div class=\"all-re\" id=\"acolor\">\n";
	code += "										<p class=\"acolor\"><i class=\"bi bi-fullscreen-exit\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-heart\"></i></p>\n";
	code += "										  <p class=\"acolor\"><i class=\"bi bi-plus-circle\"></i></p>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "				  </div>\n";
	code += "			  </div>\n";
	code += "		</section>\n";
	code += "		<section class=\"apartplan\" >\n";
	code += "\t\t\t <div class=\"container\">\n";
	code += "				 <div class=\"row\" data-aos=\"zoom-in-down\"  data-aos-duration=\"1000\">\n";
	code += "					 <h1 class=\"heading-title\">Apartment Plans</h1>\n";
	code += "					 <div class=\"col-md-12\">\n";
	code += "						<ul class=\"nav nav-tabs\">\n";
	code += "							<li class=\"active\"><a data-toggle=\"tab\" href=\"#home\">The Studio</a></li>\n";
	code += "							<li><a data-toggle=\"tab\" href=\"#menu1\">Deluxe Portion</a></li>\n";
	code += "							<li><a data-toggle=\"tab\" href=\"#menu2\">Renthouse</a></li>\n";
	code += "							<li><a data-toggle=\"tab\" href=\"#menu3\">Top Garden</a></li>\n";
	code += "							<li><a data-toggle=\"tab\" href=\"#menu4\">Double Height</a></li>\n";
	code += "						  </ul>\n";
	code += "						  \n";
	code += "						  <div class=\"tab-content\">\n";
	code += "							<div id=\"home\" class=\"tab-pane fade in active studio\"><br>\n";
	code += "								<div class=\"jumbotron\">\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-md-6\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t   <div class=\"protion\">\n";
	code += "											   <h3>Deluxe Protion</h3>\n";
	code += "											   <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>\n";
	code += "\n";
	code += "											   <h5 class=\"horizontal_dotted_line\"><span>Total Area</span><span class=\"dot\"></span> <span> 2800</span> <span> Sq. Ft</span> </h5>\n";
	code += "\n";
	code += "					<h5 class=\"horizontal_dotted_line\"><span>Bedroom</span><span class=\"dot\"></span> <span> 2800</span> <span> Sq. Ft</span></h5>\n";
	code += "\n";
	code += "					<h5 class=\"horizontal_dotted_line\"><span>Bathroom</span><span class=\"dot\"></span> <span> 2800</span> <span> Sq. Ft</span></h5>\n";
	code += "\n";
	code += "					<h5 class=\"horizontal_dotted_line\"><span>Smoking/pets</span><span class=\"dot\"></span> <span> 2800</span> <span> Sq. Ft</span></h5>\n";
	code += "					<h5 class=\"horizontal_dotted_line\"><span>Lounge</span><span class=\"dot\"></span> <span> 2800</span> <span> Sq. Ft</span></h5>\n";
	code += "										   </div>\n";
	code += "										</div>\n";
	code += "										<div class=\"col-md-6 area-image\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t  <img class=\"img-responsive\" src=\"img/apartment-plan/area.PNG\">\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								  </div>\n";
	code += "							</div>\n";
	code += "							<div id=\"menu1\" class=\"tab-pane fade deluxe\"><br>\n";
	code += "								<div class=\"jumbotron\">\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-sm-6\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t<div class=\"dp01\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t\t <h4>Deluxe protion</h4>\n";
	code += "												 <div class=\"lavel\">\n";
	code += "													 <p>Ist-miete</p>\n";
	code += "													 <p>43711,34, c/m3</p>\n";
	code += "												 </div>\n";
	code += "												 <div class=\"progress\">\n";
	code += "													<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%;\">\n";
	code += "													  <span class=\"sr-only\">60% Complete</span>\n";
	code += "													</div>\n";
	code += "												  </div>\n";
	code += "												  <div class=\"lavel\">\n";
	code += "													<p>Ist-miete</p>\n";
	code += "													<p>N/A</p>\n";
	code += "												</div>\n";
	code += "												<div class=\"progress\">\n";
	code += "												   <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 0%;\">\n";
	code += "													 <span class=\"sr-only\">0% Complete</span>\n";
	code += "												   </div>\n";
	code += "												 </div>\n";
	code += "											</div>\n";
	code += "										</div>\n";
	code += "\n";
	code += "										<div class=\"col-sm-6\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t<div class=\"dp01\">\n";
	code += "												<h4>Kaufdaten</h4>\n";
	code += "												<div class=\"lavel\">\n";
	code += "													<p>Ist-miete</p>\n";
	code += "													<p>43711,34, c/m3</p>\n";
	code += "												</div>\n";
	code += "												<div class=\"progress\">\n";
	code += "												   <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%;\">\n";
	code += "													 <span class=\"sr-only\">80% Complete</span>\n";
	code += "												   </div>\n";
	code += "												 </div>\n";
	code += "												 <div class=\"lavel\">\n";
	code += "												   <p>Ist-miete</p>\n";
	code += "												   <p>N/A</p>\n";
	code += "											   </div>\n";
	code += "											   <div class=\"progress\">\n";
	code += "												  <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"90\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 90%;\">\n";
	code += "													<span class=\"sr-only\">90% Complete</span>\n";
	code += "												  </div>\n";
	code += "												</div>\n";
	code += "											</div>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "									<br><br>\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-md-12\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t   <div class=\"dp02\">\n";
	code += "											<div class=\"progress\">\n";
	code += "												<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"10\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%;\">\n";
	code += "												  <span class=\"sr-only\">90% Complete</span>\n";
	code += "												</div>\n";
	code += "											  </div>\n";
	code += "											  <ul>\n";
	code += "												<li><span>4.54%</span><br><span>Potentiellw Rendite</span></li>\n";
	code += "												<li><span>4.54%</span><br><span>Potentiellw Rendite</span></li>\n";
	code += "												<li><span>4.54%</span><br><span>Potentiellw Rendite</span></li>\n";
	code += "												<li><span>4.54%</span><br><span>Potentiellw Rendite</span></li>\n";
	code += "											</ul>\n";
	code += "										   </div>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "							<div id=\"menu2\" class=\"tab-pane fade\"><br>\n";
	code += "								<div class=\"jumbotron\">\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-sm-12\">\n";
	code += "											<div class=\"rentho\">\n";
	code += "												<div class=\"rent01\">\n";
	code += "													<p>Eigenwshuge</p>\n";
	code += "													<p><i class=\"bi bi-heart-fill\"></i></p>\n";
	code += "												</div>\n";
	code += "												<div class=\"container-fluid\">\n";
	code += "														<div class=\"row rent02\">\n";
	code += "													<div class=\"col-sm-7\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t <p><i class=\"bi bi-geo-alt-fill\"></i> Behad hdwef hdcd yuefww</p>\n";
	code += "														 <button class=\"btn btn-primary\">Kfz-Steliplatx</button>\n";
	code += "													</div>\n";
	code += "													<div class=\"col-sm-5\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t\t\t\t <div class=\"rp21\">\n";
	code += "															 <h1>91,0000,000<span>€</span></h1>\n";
	code += "															 <h5>Goringstos Gobots</h5>\n";
	code += "														 </div>\n";
	code += "													</div>\n";
	code += "												</div>\n";
	code += "												</div>\n";
	code += "											\n";
	code += "												<ul>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "													<li><span>91,000,0$</span><br><span>Zimmer</span></li>\n";
	code += "												</ul>\n";
	code += "\n";
	code += "												<center><button class=\"btn btn-primary fina\">Finazienrung anfordem</button></center>\n";
	code += "											</div>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "							<div id=\"menu3\" class=\"tab-pane fade topgrand\"><br>\n";
	code += "								<div class=\"jumbotron\">\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-sm-12\">\n";
	code += "											<div class=\"topgar01\">\n";
	code += "												<div class=\"topgar02\">\n";
	code += "													<div class=\"topgar03\">\n";
	code += "														<p>4.Eigenwshuge</p>\n";
	code += "														\n";
	code += "													</div>\n";
	code += "												</div>\n";
	code += "												<div class=\"topgar4\">\n";
	code += "													<div class=\"tga01\">\n";
	code += "														<p><i class=\"bi bi-cart-fill\"></i> Suppermarket</p>\n";
	code += "														<p>323m</p>\n";
	code += "												</div>\n";
	code += "												<div class=\"tga01\">\n";
	code += "													<p><i class=\"bi bi-house-fill\"></i> School</p>\n";
	code += "													<p>323m</p>\n";
	code += "													</div>\n";
	code += "													<div class=\"tga01\">\n";
	code += "													<p><i class=\"bi bi-bicycle\"></i> Public Transport</p>\n";
	code += "													<p>323m</p>\n";
	code += "												</div>\n";
	code += "												<div class=\"tga01\">\n";
	code += "													<p><i class=\"bi bi-tree-fill\"></i> Pakrs</p>\n";
	code += "													<p>323m</p>\n";
	code += "												</div>\n";
	code += "												<br>\n";
	code += "												<div class=\"btn-group\">\n";
	code += "													\n";
	code += "													<button class=\"btn btn-group\">Weiter</button>\n";
	code += "													<button class=\"btn btn-group\">Back</button>\n";
	code += "												</div>\n";
	code += "												<br><br>\n";
	code += "												</div>\n";
	code += "											</div>\n";
	code += "\n";
	code += "\t\t\t\t\t\t\t\t\t\t  \n";
	code += "											\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "												\n";
	code += "							  </div>\n";
	code += "							  <div id=\"menu4\" class=\"tab-pane fade dblheight\"><br>\n";
	code += "								<div class=\"jumbotron\">\n";
	code += "									<div class=\"row\">\n";
	code += "										<div class=\"col-sm-8\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t  <h2>Deposit Expectations</h2>\n";
	code += "											  <form class=\"form-inline\">\n";
	code += "												<div class=\"form-group\">\n";
	code += "												  <label for=\"exampleInputName2\">Deposit Expectation</label>\n";
	code += "												  <input type=\"text\" class=\"form-control\" id=\"exampleInputName2\" placeholder=\"Jane Doe\">\n";
	code += "\n";
	code += "												  <span>Minual amount 1000.0s</span>\n";
	code += "												</div>&nbsp;&nbsp;&nbsp;\n";
	code += "												<div class=\"form-group formcur\">\n";
	code += "												  <label for=\"exampleInputEmail2\">Currency</label>\n";
	code += "												  <div class=\"custom-select\" style=\"width:100px\">\n";
	code += "													<select>\n";
	code += "													  <option value=\"0\">Select Currency:</option>\n";
	code += "													  <option value=\"1\">USD</option>\n";
	code += "													  <option value=\"2\">EUR</option>\n";
	code += "													  <option value=\"3\">BTC</option>\n";
	code += "													  <option value=\"4\">BCH</option>\n";
	code += "													  <option value=\"5\">DASH</option>\n";
	code += "													  <option value=\"6\">LTC</option>\n";
	code += "													  <option value=\"7\">MCH Rover</option>\n";
	code += "													  <option value=\"8\">LTC</option>\n";
	code += "													  <option value=\"9\">ZTC</option>\n";
	code += "													  <option value=\"10\">BTC</option>\n";
	code += "													\n";
	code += "													</select>\n";
	code += "												  </div>\n";
	code += "												</div>\n";
	code += "												\n";
	code += "											  </form>\n";
	code += "\n";
	code += "\n";
	code += "											  <div class=\"sliderContainer\">\n";
	code += "												<div class=\"outinline out01\">\n";
	code += "													<p><span>Period</span></p>\n";
	code += "													<p><span>24 month under 12%</span></p>\n";
	code += "												</div>\n";
	code += "												<input type=\"range\" value=\"0\" min=\"1\" max=\"24\" id=\"slider\">\n";
	code += "												<div class=\"outinline\">\n";
	code += "													<p><span>1 months</span></p>\n";
	code += "													<p><span id=\"output\"></span><span>months</span></p>\n";
	code += "												</div>\n";
	code += "												\n";
	code += "											   </div>\n";
	code += "\n";
	code += "											   <div class=\"pout02\">\n";
	code += "												   <p>Refilling deposit</p>\n";
	code += "												   <p><i class=\"bi bi-check-circle-fill\"></i></p>\n";
	code += "											   </div>\n";
	code += "											   <div class=\"pout02\">\n";
	code += "												<p>Refilling deposit<br>\n";
	code += "												<span>The way of interest payments</span></p>\n";
	code += "												<p><i class=\"bi bi-check-circle-fill\"></i></p>\n";
	code += "											</div>\n";
	code += "											<div class=\"pout02\">\n";
	code += "												<p>Refilling deposit<br>\n";
	code += "												<span>The way of interest payments</span></p>\n";
	code += "												<p><i class=\"bi bi-check-circle-fill\"></i></p>\n";
	code += "											</div>\n";
	code += "										</div>\n";
	code += "										<div class=\"col-sm-4\">\n";
	code += "\t\t\t\t\t\t\t\t\t\t\t <div class=\"finalam\">\n";
	code += "												 <h5>Final amount</h5>\n";
	code += "												 <h4>1212,19 $</h4>\n";
	code += "												 <div class=\"fna01\">\n";
	code += "													 <p>Deposit</p>\n";
	code += "													 <p>1000 $</p>\n";
	code += "												 </div>\n";
	code += "												 <div class=\"fna01\">\n";
	code += "													<p>Deposit</p>\n";
	code += "													<p>12% <br><span>yearly</span></p>\n";
	code += "												</div>\n";
	code += "												<div class=\"fna01\">\n";
	code += "													<p>Deposit</p>\n";
	code += "													<p>12% <br><span>yearly</span></p>\n";
	code += "												</div>\n";
	code += "											 </div>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "							  </div>\n";
	code += "						  </div>\n";
	code += "\n";
	code += "					 </div>\n";
	code += "				 </div>\n";
	code += "			 </div>\n";
	code += "		</section>\n";
	code += "\n";
	code += "\n";
	code += "		<section class=\"brand-slide\">\n";
	code += "			<div id=\"bigcontainer\" class=\"container\">\n";
	code += "				<div class=\"row\"  data-aos=\"zoom-in-up\"  data-aos-duration=\"1000\">\n";
	code += "					<h1 class=\"heading-title\">Our Patners</h1>\n";
	code += "					<div class=\"col-md-12\">\n";
	code += "						 <div class=\"carousel carousel-showmanymoveone slide\" id=\"carousel123\" >\n";
	code += "							<div class=\"carousel-inner\" id=\"bootstrap-touch-slider\">\n";
	code += "								<div class=\"item active\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "										<a href=\"#\">\n";
	code += "										<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "										</a>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "								<div class=\"item\">\n";
	code += "									<div class=\"col-xs-12 col-sm-6 col-md-4\">\n";
	code += "										<div class=\"bndimg\">\n";
	code += "											<a href=\"#\">\n";
	code += "											<img src=\"img/brandslide/1.svg\" class=\"img-responsive\">\n";
	code += "											</a>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "							<a class=\"left carousel-control\" href=\"#carousel123\" data-slide=\"prev\"><i class=\"bi bi-chevron-left\"></i></a>\n";
	code += "							<a class=\"right carousel-control\" href=\"#carousel123\" data-slide=\"next\"><i class=\"bi bi-chevron-right\"></i></a>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "			\n";
	code += "			   </div>\n";
	code += "			</div>\n";
	code += "		</section>\n";
	code += "		<section class=\"education\">\n";
	code += "			<img class=\"dotpngleft\" src=\"img/dot.png\">\n";
	code += "\t\t\t<div class=\"container\">\n";
	code += "				<div class=\"row\">\n";
	code += "					<div class=\"col-md-12\">\n";
	code += "						<div class=\"jumbotron\">\n";
	code += "							<div class=\"row\">\n";
	code += "								<div class=\"col-md-6 eduport\">\n";
	code += "\t\t\t\t\t\t\t\t\t<h3>Education portal</h3>\n";
	code += "									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.\n";
	code += "										<br> <br> <br>\n";
	code += "									 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\n";
	code += "\n";
	code += "									</p>\n";
	code += "									<a href=\"#\" class=\"btn btn-primary\">to the Education Portal <i class=\"bi bi-arrow-right\"></i></a>\n";
	code += "								</div>\n";
	code += "								<div class=\"col-md-6 dotlinel\">\n";
	code += "\t\t\t\t\t\t\t\t\t<img class=\"mimage\" src=\"img/education/1.jpg\">\n";
	code += "									<div class=\"video-affect\">\n";
	code += "										<div class=\"fullsize-video-bg\">\n";
	code += "											<img class=\"videoimg\" src=\"img/education/2.jpg\">\n";
	code += "											<div class=\"inner\">\n";
	code += "												<div class=\"bg-video-wrap\">					\n";
	code += "													<a href=\"#\" class=\"play-btn\" data-toggle=\"modal\" data-target=\"#myModal\" ></a>			\n";
	code += "												</div>\n";
	code += "												\n";
	code += "											</div>\n";
	code += "											<div class=\"modal deip fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\n";
	code += "												<div class=\"modal-dialog\" role=\"document\">\n";
	code += "													<div class=\"modal-content\">\n";
	code += "													<div class=\"modal-header\">\n";
	code += "													<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"><i class=\"bi bi-x\" style=\"font-size:35px;font-weight:100;\"></i></button>\n";
	code += "													</div>\n";
	code += "													<div class=\"modal-body\">\n";
	code += "														<video controls id=\"video1\">\n";
	code += "														<source src=\"video/bed.mp4\">\n";
	code += "														\n";
	code += "														</video>\n";
	code += "													</div>\n";
	code += "													<div class=\"modal-footer\">\n";
	code += "														\n";
	code += "													</div>\n";
	code += "													</div>\n";
	code += "												</div>\n";
	code += "											</div>\n";
	code += "										</div>\n";
	code += "									</div>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "			<img class=\"dotpngright\" src=\"img/dot.png\">\n";
	code += "		</section>\n";
	code += "		<section class=\"aboutus\">\n";
	code += "			<img class=\"dotpngleft\" src=\"img/dot.png\">\n";
	code += "\t\t\t<div class=\"container\">\n";
	code += "				<div class=\"row\"  data-aos=\"zoom-in\"  data-aos-duration=\"1000\">\n";
	code += "					<div class=\"col-md-12\">\n";
	code += "						<div class=\"jumbotron\">\n";
	code += "							<div class=\"row\">\n";
	code += "\t\t\t\t\t\t\t\t  <div class=\"col-md-6\">\n";
	code += "									  <div id=\"display\" class=\"modalll\">\n";
	code += "										\n";
	code += "										  <img src='img/about/1.jpg'  class=\"mimage modalImage\" id=\"img01\">\n";
	code += "									  </div>\n";
	code += "									\n";
	code += "									<div class=\"vartcal\">\n";
	code += "										<ul>\n";
	code += "											<li><img  src='img/about/1.jpg' class=\"ImgThumbnail\"></li>\n";
	code += "											<li><img src='img/about/2.jpg' class=\"ImgThumbnail\"></li>\n";
	code += "											<li><img src='img/about/3.jpg'  class=\"ImgThumbnail\"></li>\n";
	code += "										</ul>\n";
	code += "									</div>\n";
	code += "								  </div>\n";
	code += "								  <div class=\"col-md-6 aboutcontent\">\n";
	code += "									  <center><a href=\"#\" class=\"btn btn-primary\">About us</a></center>\n";
	code += "\t\t\t\t\t\t\t\t\t  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry.\n";
	code += "										<br>\n";
	code += "										<br>\n";
	code += "										  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.\n";
	code += "										  <br><br>\n";
	code += "										  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.\n";
	code += "									  </p>\n";
	code += "								</div>\n";
	code += "		\t\t\t\t\t</div>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "			<img class=\"dotpngright\" src=\"img/dot.png\">\n";
	code += "		</section>\n";
	code += "		<section class=\"financ\">\n";
	code += "\t\t\t<div class=\"container\">\n";
	code += "				<div class=\"row\"  data-aos=\"zoom-in\"  data-aos-duration=\"1000\">\n";
	code += "					<div class=\"col-md-12\">\n";
	code += "						<div class=\"jumbotron\">\n";
	code += "							<div class=\"row\">\n";
	code += "								<h1 class=\"heading-title\">Financing</h1>\n";
	code += "\t\t\t\t\t\t\t\t  <div class=\"col-md-6 rotetimg\">\n";
	code += "									\n";
	code += "								\t   <div class=\"fast\">\n";
	code += "										   <img class=\"dotpngleft financingdotimg\" src=\"img/dot.png\">\n";
	code += "										   <ul>\n";
	code += "											   <li><img class=\"img-responsive\" src=\"img/financ/1.jpg\"></li>\n";
	code += "											   <li><img  class=\"img-responsive\" src=\"img/financ/2.jpg\"></li>\n";
	code += "										   </ul>\n";
	code += "									   </div>\n";
	code += "									   <div class=\"second\">\n";
	code += "										<ul>\n";
	code += "											<li><img src=\"img/financ/3.jpg\"></li>\n";
	code += "											<li><img src=\"img/financ/4.jpg\"></li>\n";
	code += "										</ul>\n";
	code += "									</div>\n";
	code += "								  </div>\n";
	code += "								  <div class=\"col-md-6 intertitle\">\n";
	code += "									  <div class=\"he1\">\n";
	code += "										  <h4>Interhype Baufinancing</h4>\n";
	code += "									\t  <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.</p>\n";
	code += "									\t <h5>Interhype Baufinancing</h5>\n";
	code += "									  </div>\n";
	code += "									  <div class=\"he2\">\n";
	code += "										<h4>Interhype Baufinancing</h4>\n";
	code += "										<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy.</p>\n";
	code += "									   <h5>Interhype Baufinancing</h5>\n";
	code += "									</div>\n";
	code += "									 \n";
	code += "								</div>\n";
	code += "		\t\t\t\t\t</div>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "		</section>\n";
	code += "\n";
	code += "		<section class=\"manager\">\n";
	code += "		\t<div class=\"container\">\n";
	code += "				\n";
	code += "					<div class=\"row mg-bg\"  data-aos=\"zoom-in-down\"  data-aos-duration=\"1000\">\n";
	code += "						<div class=\"col-md-12 slideanim \">\n";
	code += "							<center>\n";
	code += "								<h1 >Realty Manager</h1>\n";
	code += "								<p>All frms,propetics and tecnts in one place.</p>					\n";
	code += "							</center><br>\n";
	code += "							<center>\n";
	code += "							<div class=\"row\">\n";
	code += "								<div class=\"col-md-12\">\n";
	code += "									<center><a href=\"#\" class=\"btn btn-primary\" role=\"button\">Realty Manager</a></center>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						   </center>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "				\n";
	code += "			</div>\n";
	code += "		</section>\n";
	code += "		<section class=\"blog\">\n";
	code += "		\t<div class=\"container\">\n";
	code += "				<div class=\"row mainth-blog\">\n";
	code += "				\t<div class=\"col-md-4 col-sm-4 col-xs-12\">\n";
	code += "					\t<a class=\"thumbnail-blog\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\" data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"500\">\n";
	code += "								<img class=\"main-img\" src=\"img/blog/1.jfif\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "									<h2>Interhype baufinancing</h2>\n";
	code += "									\n";
	code += "									<p class=\"beds\">Construction is a complex process that involves the expertise of many professionals, from laying the foundations of the building to the last stroke of a paintbrush, a building goes through various phases which are necessary for giving a building the complete shape. If some of the important phases of the construction are missed or aren’t given the proper attention the quality and the durability of the building can be hampered. Therefore, it is necessary that an owner of a house or commercial building should have information regarding the structural, electrical and mechanical aspects of the building.</p>\n";
	code += "									<hr style=\"margin:0;\">\n";
	code += "									<h4>See More</h4>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "					<div class=\"col-md-4 col-sm-4 col-xs-12\">\n";
	code += "					\t<a class=\"thumbnail-blog\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\" data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"700\">\n";
	code += "								<img class=\"main-img\" src=\"img/blog/2.jpg\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "									<h2>Interhype baufinancing</h2>\n";
	code += "									\n";
	code += "									<p class=\"beds\">Construction is a complex process that involves the expertise of many professionals, from laying the foundations of the building to the last stroke of a paintbrush, a building goes through various phases which are necessary for giving a building the complete shape. If some of the important phases of the construction are missed or aren’t given the proper attention the quality and the durability of the building can be hampered. Therefore, it is necessary that an owner of a house or commercial building should have information regarding the structural, electrical and mechanical aspects of the building.</p>\n";
	code += "									<hr style=\"margin:0;\">\n";
	code += "									<h4>See More</h4>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "					<div class=\"col-md-4 col-sm-4 col-xs-12\">\n";
	code += "					\t<a class=\"thumbnail-blog\" href=\"#\">\n";
	code += "							<div class=\"thumbnail\" data-aos=\"fade-up\" data-aos-easing=\"linear\"\n";
	code += "							data-aos-duration=\"900\">\n";
	code += "								<img class=\"main-img\" src=\"img/blog/3.jpg\" alt=\"...\">\n";
	code += "								<div class=\"caption\">\n";
	code += "									<h2>Interhype baufinancing</h2>\n";
	code += "									\n";
	code += "									<p class=\"beds\">Construction is a complex process that involves the expertise of many professionals, from laying the foundations of the building to the last stroke of a paintbrush, a building goes through various phases which are necessary for giving a building the complete shape. If some of the important phases of the construction are missed or aren’t given the proper attention the quality and the durability of the building can be hampered. Therefore, it is necessary that an owner of a house or commercial building should have information regarding the structural, electrical and mechanical aspects of the building.</p>\n";
	code += "									<hr style=\"margin:0;\">\n";
	code += "									<h4>See More</h4>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</a>\n";
	code += "					</div>\n";
	code += "\n";
	code += "					\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "	\t</section>\n";
	code += "\n";
	code += "		<section class=\"testimonials\" data-aos=\"zoom-in\"  data-aos-duration=\"1000\">\n";
	code += "\t\t\t <div class=\"container\">\n";
	code += "				 <div class=\"row\">\n";
	code += "					<h1 class=\"heading-title\">Our Testimonials</h1>\n";
	code += "					 <div class=\"col-md-12\">\n";
	code += "						<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n";
	code += "\t\t\t\t\t\t\t<ol class=\"carousel-indicators\">\n";
	code += "								<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n";
	code += "								<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n";
	code += "								<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n";
	code += "							  </ol>\n";
	code += "							<!-- Wrapper for carousel items -->\n";
	code += "							<div class=\"carousel-inner\">\n";
	code += "								<div class=\"item carousel-item active\">\n";
	code += "									<div class=\"mainallslide\">\n";
	code += "										<span class=\"span1\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "										<div class=\"img-box\"><img src=\"img/test/1.jpg\" alt=\"\"></div>\n";
	code += "										<br><br><br><br><br><br>\n";
	code += "										<h4 class=\"carousel-title\">Mike van Wijnen</h4>\n";
	code += "										<p class=\"overview\">Tibugh . Netherlands</p>\n";
	code += "										<p class=\"testimonial\"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu<br> sem tempor, varius quam at, luctus dui. Mauris magna metus,<br> dapibus nec turpis vel, semper malesuada ante. aliquet.</p>\n";
	code += "										<span class=\"span2\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "			\n";
	code += "								<div class=\"item carousel-item\">\n";
	code += "									<div class=\"mainallslide\">\n";
	code += "										<span class=\"span1\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "										<div class=\"img-box\"><img src=\"img/test/1.jpg\" alt=\"\"></div>\n";
	code += "										<br><br><br><br><br><br>\n";
	code += "										<h4 class=\"carousel-title\">Mike van Wijnen</h4>\n";
	code += "										<p class=\"overview\">Tibugh . Netherlands</p>\n";
	code += "										<p class=\"testimonial\"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu<br> sem tempor, varius quam at, luctus dui. Mauris magna metus,<br> dapibus nec turpis vel, semper malesuada ante. aliquet.</p>\n";
	code += "										<span class=\"span2\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "			\n";
	code += "								<div class=\"item carousel-item\">\n";
	code += "									<div class=\"mainallslide\">\n";
	code += "										<span class=\"span1\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "										<div class=\"img-box\"><img src=\"img/test/1.jpg\" alt=\"\"></div>\n";
	code += "										<br><br><br><br><br><br>\n";
	code += "										<h4 class=\"carousel-title\">Mike van Wijnen</h4>\n";
	code += "										<p class=\"overview\">Tibugh . Netherlands</p>\n";
	code += "										<p class=\"testimonial\"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu<br> sem tempor, varius quam at, luctus dui. Mauris magna metus,<br> dapibus nec turpis vel, semper malesuada ante. aliquet.</p>\n";
	code += "										<span  class=\"span2\"><i class=\"bi bi-pause-fill\"></i></span>\n";
	code += "								\t</div>\n";
	code += "								</div>\n";
	code += "			\n";
	code += "							</div>\n";
	code += "							<!-- Carousel controls -->\n";
	code += "							<a class=\"carousel-control left carousel-control-prev\" href=\"#myCarousel\" data-slide=\"prev\">\n";
	code += "								<i class=\"fa fa-angle-left\"></i>\n";
	code += "							</a>\n";
	code += "							<a class=\"carousel-control right carousel-control-next\" href=\"#myCarousel\" data-slide=\"next\">\n";
	code += "								<i class=\"fa fa-angle-right\"></i>\n";
	code += "							</a>\n";
	code += "						</div>\n";
	code += "					 </div>\n";
	code += "				 </div>\n";
	code += "			 </div>\n";
	code += "		</section>\n";
	code += "\n";
	code += "		<section class=\"register\">\n";
	code += "			<div class=\"container\">\n";
	code += "				<div class=\"row\">\n";
	code += "					<div class=\"col-md-12\">\n";
	code += "						<div class=\"jumbotron\">\n";
	code += "							<div class=\"row\" data-aos=\"zoom-in\"  data-aos-duration=\"1000\">\n";
	code += "								<h1 class=\"heading-title\">Registerering</h1>\n";
	code += "								<div class=\"col-md-6\">\n";
	code += "\t\t\t\t\t\t\t\t\t   <img class=\"img-responsive\" src=\"img/reg/1.PNG\">\n";
	code += "							  	</div>\n";
	code += "								<div class=\"col-md-6 right-p\">\n";
	code += "\t\t\t\t\t\t\t\t\t<p>\n";
	code += "										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus,dapibus nec turpis vel, semper malesuada ante. aliquet.\n";
	code += "										\n";
	code += "									</p>\n";
	code += "									<input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"Email\">\n";
	code += "									<p>\n";
	code += "										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus,dapibus nec turpis vel, semper malesuada ante. aliquet.\n";
	code += "										<br><br>\n";
	code += "										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus,dapibus nec turpis vel, semper malesuada ante. aliquet.\n";
	code += "\n";
	code += "										\n";
	code += "									</p>\n";
	code += "									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n";
	code += "\n";
	code += "									<label class=\"custom-checkbox\">For stemmme cha bainh wah taniya\n";
	code += "										<input type=\"checkbox\">\n";
	code += "										<span class=\"checkmark\"></span>\n";
	code += "									</label>\n";
	code += "\n";
	code += "									<a href=\"#\" class=\"btn btn-primary\">Abonnimuneren</a>\n";
	code += "								</div>\n";
	code += "							</div>\n";
	code += "						</div>\n";
	code += "					</div>\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "		</section>\n";
	code += "\n";
	code += "		<footer>\n";
	code += "			<div class=\"container\">\n";
	code += "				<div class=\"row\">\n";
	code += "					<div class=\"col-md-3 col-sm-6 logocontent\">\n";
	code += "						  <img src=\"img/logo/Asset 1SVG.svg\">\n";
	code += "\t\t\t\t\t\t  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus,dapibus nec turpis vel, semper malesuada ante. aliquet.</p>\n";
	code += "						  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus,dapibus nec turpis vel, semper malesuada ante. aliquet.</p>\n";
	code += "					</div>\n";
	code += "					<div class=\"col-md-3 col-sm-6 dbll\">\n";
	code += "						<h3>Promised country</h3>\n";
	code += "						<div class=\"line\"></div>\n";
	code += "						<br>\n";
	code += "							<p><a href=\"#\">Promised Land UG</a></p>\n";
	code += "							<p><a href=\"#\">Metzlerstr,26</a></p>\n";
	code += "							<p><a href=\"#\">60594 Frankfrut am Main</a></p>\n";
	code += "					</div>\n";
	code += "					<div class=\"col-md-3 col-sm-6 dbll\">\n";
	code += "						<h3>Service</h3>\n";
	code += "						<div class=\"line service-line\"></div>\n";
	code += "						<br>\n";
	code += "							<p><a href=\"#\">Property</a></p>\n";
	code += "							<p><a href=\"#\">Finance</a></p>\n";
	code += "							<p><a href=\"#\">Education</a></p>\n";
	code += "							<p><a href=\"#\">Reality\t\t\t  Manager</a></p>\n";
	code += "					</div>\n";
	code += "					<div class=\"col-md-3 col-sm-6 dbll\">\n";
	code += "						<h3>legal</h3>\n";
	code += "						<div class=\"line legal-line\"></div>\n";
	code += "						<br>\n";
	code += "							<p><a href=\"#\">Imprint</a></p>\n";
	code += "							<p><a href=\"#\">Data protection</a></p>\n";
	code += "							<p><a href=\"#\">Terms and Condition</a></p>\n";
	code += "							<p><a href=\"#\">Disclaimer</a></p>\n";
	code += "					</div>\n";
	code += "				</div>\n";
	code += "			</div>\n";
	code += "			<div class=\"social\">\n";
	code += "				\n";
	code += "					<center>\n";
	code += "					<ul>\n";
	code += "						<li><span class=\"social-icon social-facebook\"><i class=\"fa fa-facebook\"></i></span></li>\n";
	code += "						<li><span class=\"social-icon social-google\"><i class=\"fa fa-pinterest\"></i></span></li>\n";
	code += "						<li><span class=\"social-icon social-linkedin\"><i class=\"fa fa-linkedin\"></i></span></li>\n";
	code += "						<li><span class=\"social-icon social-instagram\"><i class=\"fa fa-instagram\"></i></span></li>\n";
	code += "						<li><span class=\"social-icon social-twitter\"><i class=\"fa fa-twitter\"></i></span></li>\n";
	code += "						<li><span class=\"social-icon social-youtube\"><i class=\"fa fa-youtube\"></i></span></li>\n";
	code += "					</ul>\n";
	code += "				</center>\n";
	code += "			</div>\n";
	code += "			<br>\n";
	code += "		</footer>\n";
	code += "		<p class=\"back-to-top\"><i class=\"bi bi-arrow-down-short\"></i></p>\n";
	code += "\t\t\t<script src=\"js/bootstrap.js\"><\\/script>\n";
	code += "\t\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"><\\/script>\n";
	code += "\t\t\t<script src=\"js/bootstrap.min.js\"><\\/script>\n";
	code += "			<script src=\"js/index.js\"><\\/script>\n";
	code += "			<script src=\"js/slide.js\"><\\/script>\n";
	code += "			<script  src=\"js/touch.js\"><\\/script>\n";
	code += "			<script src=\"js/video.js\"><\\/script>\n";
	code += "			<script src=\"https://unpkg.com/aos@2.3.1/dist/aos.js\"><\\/script>\n";
	code += "			<script>\n";
	code += "				var min_w = 300;\n";
	code += "	var vid_w_orig;\n";
	code += "	var vid_h_orig;\n";
	code += "	\n";
	code += "	$(function() {\n";
	code += "	\n";
	code += "		vid_w_orig = parseInt($('video').attr('width'));\n";
	code += "		vid_h_orig = parseInt($('video').attr('height'));\n";
	code += "	\n";
	code += "		$(window).resize(function () { fitVideo(); });\n";
	code += "		$(window).trigger('resize');\n";
	code += "	\n";
	code += "	});\n";
	code += "	\n";
	code += "	function fitVideo() {\n";
	code += "	\n";
	code += "		$('#video-viewport').width($('.fullsize-video-bg').width());\n";
	code += "		$('#video-viewport').height($('.fullsize-video-bg').height());\n";
	code += "	\n";
	code += "		var scale_h = $('.fullsize-video-bg').width() / vid_w_orig;\n";
	code += "		var scale_v = $('.fullsize-video-bg').height() / vid_h_orig;\n";
	code += "		var scale = scale_h > scale_v ? scale_h : scale_v;\n";
	code += "	\n";
	code += "		if (scale * vid_w_orig < min_w) {scale = min_w / vid_w_orig;};\n";
	code += "	\n";
	code += "		$('#videol').width(scale * vid_w_orig);\n";
	code += "		$('#videol').height(scale * vid_h_orig);\n";
	code += "	\n";
	code += "		$('#video-viewport').scrollLeft(($('video').width() - $('.fullsize-video-bg').width()) / 2);\n";
	code += "		$('#video-viewport').scrollTop(($('video').height() - $('.fullsize-video-bg').height()) / 2);\n";
	code += "	\n";
	code += "	};\n";
	code += "				<\\/script>\n";
	code += "			<script>/////////////........content animate\n";
	code += "\n";
	code += "				AOS.init(); \n";
	code += "				 <\\/script>\n";
	code += "				</body>\n";
	code += "\t</body>\n";
	code += "</html>\n";
	return code;
}


document.getElementById("js_html").innerText = js_thml();
document.getElementById("html-text").value = js_thml();
</script>
